name = "yamanashi-event-sync-backend"
main = "src/index.ts"
compatibility_date = "2026-07-18"

[vars]
ALLOWED_ORIGIN = "https://hub.yamanashi.dev"

[[kv_namespaces]]
binding = "SYNC_KV"
id = "0af76ff745a54e12ab0bc3e8f4c20275"
preview_id = "4d52e592dca74999b4b8903bb268fec0"
